modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="minieffects"
version="${file.jarVersion}"
displayName="Mini Effects"
authors="Snownee"

[modproperties.minieffects]
    catalogueItemIcon="minecraft:potion" #Support for Catalogue mod
